NDefines.NRailwayGun.RAILWAY_GUN_RANGE = 10
NDefines.NRailwayGun.BASE_CAPTURE_CHANCE = 1
NDefines.NRailwayGun.ATTACK_TO_BOMBARDMENT_MODIFIER_FACTOR = 0.8
NDefines.NRailwayGun.ATTACK_TO_INITIATIVE_MODIFIER_FACTOR = 0.8
NDefines.NRailwayGun.ATTACK_TO_SOFT_ATTACK_MODIFIER_FACTOR = 0.8
